#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : zake
Version  : 0.2.2
Release  : 26
URL      : http://pypi.debian.net/zake/zake-0.2.2.tar.gz
Source0  : http://pypi.debian.net/zake/zake-0.2.2.tar.gz
Summary  : A python package that works to provide a nice set of testing utilities for the kazoo library.
Group    : Development/Tools
License  : Apache-2.0
Requires: zake-python
Requires: kazoo
Requires: six
BuildRequires : kazoo
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six

%description
====

%package python
Summary: python components for the zake package.
Group: Default

%description python
python components for the zake package.


%prep
%setup -q -n zake-0.2.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1503089688
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1503089688
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
